/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Box.glb 
*/

import React, {useEffect, useRef, useState} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'

function Box(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Box.glb')
  const { actions , names} = useAnimations(animations, group)

  useEffect(() => {
    actions[names[1]].play()
  }, [])


  return (
    <group
        ref={group}
        {...props}
        dispose={null}
    >
      <group name="Scene">
        <group
          name="Armature"
          position={[0, -2.5, 0]}
          rotation={[1,0,0]}
        >
          <primitive object={nodes.Bone} />
          <skinnedMesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Cube.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Box.glb')


export default Box
